<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>ab47b656-127c-4d68-9fbd-2101dfed0bc5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FalandoSobre.Domain\FalandoSobre.Domain.csproj" />
    <ProjectReference Include="..\FalandoSobre.Infrastructure\FalandoSobre.Infrastructure.csproj" />
    <ProjectReference Include="..\FalandoSobre.SharedKernel\FalandoSobre.SharedKernel.csproj" />
    <ProjectReference Include="..\FalandoSobre.Web\FalandoSobre.Web\FalandoSobre.Web.csproj" />
    <ProjectReference Include="..\FalandoSobreApplication\FalandoSobreApplication.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\ProfilesPhotos\Uploads\" />
    <Folder Include="wwwroot\ReportImages\Uploads\" />
  </ItemGroup>

</Project>
